alias ga="git add . --all"
alias gca="git commit --amend"
alias gch="git checkout"
alias gco="git commit -a"
alias gf="git fetch"
alias gpl="git pull origin"
alias gps="git push origin"
alias gs="git status"
