#!/usr/bin/env bash

# Wrapper around foreman with `dotenv` gem for setting up the env variables.
# It is to reference envs in the .env file i.e.
#
#   ```
#   foo=2
#   bar=$foo
#   ```
#
# It passes `/dev/null` as env file path to foreman so it won't load default .env file.
#
# requires:
#   - foreman
#   - dotenv

dotenv -f ./.env.local 'foreman start -f Procfile.local -e /dev/null'
