#!/usr/bin/env bash

redis-down() {
  app_name=$1
  socket_file="/tmp/redis/${app_name}.socket"
  log_file="/tmp/redis/${app_name}.log"
  if [ ! -e $socket_file ]; then
    echo "Redis: ${app_name} is already shut downed"
    exit 0
  fi
  redis-cli -s ${socket_file} shutdown
  rm -rf ${socket_file} ${log_file}
  echo "Redis: ${app_name} shut downed"
}

redis-down $1
